import { useEffect, useState } from "react";
import Head from "next/head";
import BaseLink from "../components/BaseLink";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

function Hack() {
  const router = useRouter();
  // useEffect(() => {
  //   const { pathname } = window.location;
  //   console.log(pathname);
  //   const ipfsMatch = new RegExp("/.*\\/Qm\\w{44}\\//");
  //   console.log(pathname === ipfsMatch ? "ipfs" : "not ipfs");
  //   router.push(ipfsMatch ? "/hack?ipfs=true" : "/hack/", undefined, {
  //     shallow: true,
  //   });
  // }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Hack</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>hack the planet!</h1>

        {typeof window !== "undefined" ? window.location.pathname : ""}
        <BaseLink href='/'>
          <a>Back!</a>
        </BaseLink>
      </main>
    </div>
  );
}

export default Hack;
