import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Hack() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Hack</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>hack the planet!</h1>

        <Link href='/'>
          <a>Back!</a>
        </Link>
      </main>
    </div>
  );
}
