import { useEffect } from "react";
import Head from "next/head";
import BaseLink from "../components/BaseLink";
import styles from "../styles/Home.module.css";

export default function Hack() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Hack</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>hack the planet!</h1>
        Hostname:{" "}
        {typeof window !== "undefined" ? window.location.pathname : ""}
        <BaseLink href='/'>
          <a>Back!</a>
        </BaseLink>
      </main>
    </div>
  );
}
